name: Dev Build

on:
  push:
    branches: [ dev ]
    paths:
      - 'OBSControl/**'
      - '.github/workflows/BuildDev.yml'
      - 'packages/**'
  pull_request:
    branches: [ dev ]
    paths: 'OBSControl/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
        ref: dev
    - name: Setup dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: GetStrippedRefs
      env:
        FILES_URL: ${{ secrets.BSFILES_URL }}
      run: wget --no-check-certificate "$FILES_URL" -q -O bsfiles.zip
    - name: ExtractRefs
      run: unzip -q bsfiles.zip -d ./Refs/BeatSaber
    - name: Build
      id: Build
      env: 
        FrameworkPathOverride: /usr/lib/mono/4.8-api
      run: dotnet build --configuration Release -p:DisableZipRelease=true -p:DisableCopyToPlugins=true -p:CIBuild=true
    - name: Echo Filename
      run: echo $BUILDTEXT \($ASSEMBLYNAME\)
      env:
        BUILDTEXT: Filename=${{ steps.Build.outputs.filename }}
        ASSEMBLYNAME: AssemblyName=${{ steps.Build.outputs.assemblyname }}
    - name: Upload Artifact
      uses: actions/upload-artifact@v1
      with:
        name: ${{ steps.Build.outputs.filename }}
        path: ./OBSControl/bin/Release/Final
