name: Unit Tests - Dev

on:
  push:
    branches: [ dev ]
    paths: 
      - 'OBSControl/**'
      - 'OBSControlTests/**'
      - '.github/workflows/UnitTests-Dev.yml'
      - 'packages/**'
  pull_request:
    branches: [ dev ]
    paths: 
      - 'OBSControl/**'
      - 'OBSControlTests/**'
      - 'packages/**'

jobs:
  tests:
    name: Unit Testing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
          ref: dev
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.101
      - name: GetStrippedRefs
        env:
          FILES_URL: ${{ secrets.BSFILES_URL }}
        run: wget --no-check-certificate "$FILES_URL" -q -O bsfiles.zip
      - name: ExtractRefs
        run: unzip -q bsfiles.zip -d ./Refs/BeatSaber
      - name: Test
        env:
          FrameworkPathOverride: /usr/lib/mono/4.8-api
        run: dotnet test --logger GitHubActions
